version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_db
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-ui
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
